version: 2
jobs:
  build:
    branches:
      only:
        - angular-ui
    working_directory: ~/code-radar-visualization-demo
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-test
          command: yarn run notest
      - run:
          name: angular-build
          command: yarn run build:demo --no-progress
      - run:
          name: ghpages-publish-demo
          command: yarn run ghpages:demo